"""esquema inicial

Revision ID: 50a199eefc89
Revises: 
Create Date: 2026-08-16 16:20:14.481486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a199eefc89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_caracteristicas_hotel_id_caracteristica'), 'caracteristicas_hotel', ['id_caracteristica'], unique=False)
    op.create_index(op.f('ix_categoria_servicio_id_categoria'), 'categoria_servicio', ['id_categoria'], unique=False)
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_destinos_id_destino'), 'destinos', ['id_destino'], unique=False)
    op.create_index(op.f('ix_empleados_id_empleado'), 'empleados', ['id_empleado'], unique=False)
    op.drop_constraint('habitaciones_id_hotel_numero_habitacion_key', 'habitaciones', type_='unique')
    op.drop_index('idx_habitaciones_hotel', table_name='habitaciones')
    op.create_index(op.f('ix_habitaciones_id_habitacion'), 'habitaciones', ['id_habitacion'], unique=False)
    op.create_unique_constraint('uq_hotel_numero', 'habitaciones', ['id_hotel', 'numero_habitacion'])
    op.create_index(op.f('ix_historial_reservas_id_historial'), 'historial_reservas', ['id_historial'], unique=False)
    op.create_index(op.f('ix_hoteles_id_hotel'), 'hoteles', ['id_hotel'], unique=False)
    op.create_index(op.f('ix_metodos_pago_id_metodo'), 'metodos_pago', ['id_metodo'], unique=False)
    op.alter_column('pagos', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_pagos_id_pago'), 'pagos', ['id_pago'], unique=False)
    op.alter_column('paquetes', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_paquetes_id_paquete'), 'paquetes', ['id_paquete'], unique=False)
    op.alter_column('preferencias_cliente', 'intereses',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.create_index(op.f('ix_preferencias_cliente_id_preferencia'), 'preferencias_cliente', ['id_preferencia'], unique=False)
    op.drop_constraint('preferencias_cliente_id_cliente_fkey', 'preferencias_cliente', type_='foreignkey')
    op.create_foreign_key(None, 'preferencias_cliente', 'clientes', ['id_cliente'], ['id_cliente'])
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.create_index(op.f('ix_recuperacion_password_id_recuperacion'), 'recuperacion_password', ['id_recuperacion'], unique=False)
    op.alter_column('reservas', 'numero_personas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('idx_reservas_cliente', table_name='reservas')
    op.drop_index('idx_reservas_estado', table_name='reservas')
    op.create_index(op.f('ix_reservas_id_reserva'), 'reservas', ['id_reserva'], unique=False)
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.alter_column('servicios', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('servicios', 'capacidad_maxima',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_servicios_id_servicio'), 'servicios', ['id_servicio'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_id_sesion'), 'sesiones_usuario', ['id_sesion'], unique=False)
    op.create_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), 'tipo_habitacion', ['id_tipo_habitacion'], unique=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_usuarios_correo', table_name='usuarios')
    op.drop_index('idx_usuarios_username', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.create_index('idx_usuarios_username', 'usuarios', ['username'], unique=False)
    op.create_index('idx_usuarios_correo', 'usuarios', ['correo_electronico'], unique=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), table_name='tipo_habitacion')
    op.drop_index(op.f('ix_sesiones_usuario_id_sesion'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_servicios_id_servicio'), table_name='servicios')
    op.alter_column('servicios', 'capacidad_maxima',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicios', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_index(op.f('ix_reservas_id_reserva'), table_name='reservas')
    op.create_index('idx_reservas_estado', 'reservas', ['estado'], unique=False)
    op.create_index('idx_reservas_cliente', 'reservas', ['id_cliente'], unique=False)
    op.alter_column('reservas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reservas', 'numero_personas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_recuperacion_password_id_recuperacion'), table_name='recuperacion_password')
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.drop_constraint(None, 'preferencias_cliente', type_='foreignkey')
    op.create_foreign_key('preferencias_cliente_id_cliente_fkey', 'preferencias_cliente', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
    op.drop_index(op.f('ix_preferencias_cliente_id_preferencia'), table_name='preferencias_cliente')
    op.alter_column('preferencias_cliente', 'intereses',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_paquetes_id_paquete'), table_name='paquetes')
    op.alter_column('paquetes', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_pagos_id_pago'), table_name='pagos')
    op.alter_column('pagos', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_metodos_pago_id_metodo'), table_name='metodos_pago')
    op.drop_index(op.f('ix_hoteles_id_hotel'), table_name='hoteles')
    op.drop_index(op.f('ix_historial_reservas_id_historial'), table_name='historial_reservas')
    op.drop_constraint('uq_hotel_numero', 'habitaciones', type_='unique')
    op.drop_index(op.f('ix_habitaciones_id_habitacion'), table_name='habitaciones')
    op.create_index('idx_habitaciones_hotel', 'habitaciones', ['id_hotel'], unique=False)
    op.create_unique_constraint('habitaciones_id_hotel_numero_habitacion_key', 'habitaciones', ['id_hotel', 'numero_habitacion'])
    op.drop_index(op.f('ix_empleados_id_empleado'), table_name='empleados')
    op.drop_index(op.f('ix_destinos_id_destino'), table_name='destinos')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_categoria_servicio_id_categoria'), table_name='categoria_servicio')
    op.drop_index(op.f('ix_caracteristicas_hotel_id_caracteristica'), table_name='caracteristicas_hotel')
    # ### end Alembic commands ###
