name: AlecTours Docker CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker:
    name: Docker Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker compose version

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker images
        run: docker compose build
